# Generated by Django 5.0.1 on 2024-02-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearInSchool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('pfw_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.ethnicity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.gender')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.major')),
                ('year_in_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.yearinschool')),
            ],
        ),
    ]
